# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterPage', '0002_auto_20170922_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_priority',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
