# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterPage', '0003_job_job_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
